### ISSUE TITLE
Error when starting homebrew

### ISSUE THREAD

**Issue by CodingKoopa** [noahc3/sdsetup-switch#8]
When opening SDSetup, this error occurs:
![2019031701523500-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/13039555/54485992-662c1e00-4858-11e9-85cd-d8a8ad8728c8.jpg)
There was no log file in the `switch` directory of my micro SD card.

Random system specs:
- FW: 7.0.1.
- SD Card: 32GB, exFAT.
- CFW Distrobution: Kozmos v11.11.1, including:
  - hbmenu v3.0.1
  - SDSetup v0.3

**Comment by noahc3** [comment]
welp that sucks

i'll see if its a quick fix but if its not i might not be able to work on it for a while.

**Comment by noahc3** [comment]
uh so apparently it works now for some reason.

i have literally no idea why or how, but i guess i can close this...

**Comment by CodingKoopa** [comment]
Yeah works for me too now.

**Comment by tonyrojas2007** [comment]
Still happening for me.

FW: 8.1.0
SD Card: 400GB, FAT32.
CFW: Kozmos v13.2.1, including:
hbmenu v3.1.0
SDSetup v0.3
Kosmos Toolbox - v2.1.0

Also, no log is created in /switch or /Homebrew_SD_Setup and LoveDebug is empty.

**Comment by noahc3** [comment]
Highly recommend not using this app for the time being. It needs a complete rewrite.
