### ISSUE TITLE
Error with 1 of the repos

### ISSUE THREAD

**Issue by RiPPERD** [noahc3/sdsetup-switch#9]
hello, there seems to be an issue with one of the emulator repos... im not sure which one... maybe one of the retroarch emulators... i select all and it says download failed... take of all the emulators including the standalone ones and download works fine...

**Comment by RiPPERD** [comment]
UPDATE: its defo one of the retroarch repos as just tested with other emulators ticked

**Comment by noahc3** [comment]
https://github.com/noahc3/SDSetup/issues/85
